### ISSUE TITLE
[esports] 赛程插件计算日期差的方式有错误

### ISSUE THREAD

**Issue by Jerry-FaGe** [beiyuouo/bbot#9]
`_query.py`中

> day_delta = (query_day - datetime.datetime.today()).days

`query_day`是不包含时分秒信息的，而`datetime.datetime.today()`包含时分秒信息，这样先做差后取天的结果就会有不足一天的情况从而被舍掉，导致计算出来的天数差-1（比如`query_day`为20号`datetime.datetime.today()`为19号中午12点，这样做差会得到0天12小时，取days为0，和实际1不符）

建议改为

> ~~day_delta = query_day.day - datetime.datetime.today().day~~ (丢人)

> (query_day.date() - datetime.datetime.now().date()).days

========================================================
另外，在我改好后命令输入`赛程 ^[0-9]$`时，会返回两条信息，一条今天，一条计算后的那天，不知道就是这么设计的还是bug

命令输入`赛程 [4位数，比如0221]`时，会正常返回一条信息，就是那天的赛程，但是控制台报错

> 02-20 14:47:11 [ERROR] nonebot | Running matcher <Matcher from esports, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 39, in <module>
    nonebot.run(app="bot:app")
  File "/home/.local/lib/python3.8/site-packages/nonebot/__init__.py", line 217, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 118, in run
    uvicorn.run(app or self.server_app,
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/home/.local/lib/python3.8/site-packages/nonebot/message.py", line 170, in _run_matcher
    await matcher.run(bot, event, state)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 496, in run
    await self.run_handler(handler, bot, event, state_)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 481, in run_handler
    await handler(
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 365, in wrapper
    await matcher.run_handler(func, bot, event, state)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 481, in run_handler
    await handler(
  File "src/plugins/esports/_query.py", line 80, in handle_event
    query_day = datetime.datetime.strptime(args, "%Y%m%d")
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '21' does not match format '%Y%m%d'

命令输入`赛程 [8位数，比如20210222]`时，会返回两条信息，一条是 **21020202**赛程：比赛数据也不对，另一条是20210222赛程，并且控制台也会报错

> 02-20 14:47:44 [ERROR] nonebot | Running matcher <Matcher from esports, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 39, in <module>
    nonebot.run(app="bot:app")
  File "/home/.local/lib/python3.8/site-packages/nonebot/__init__.py", line 217, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 118, in run
    uvicorn.run(app or self.server_app,
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
> File "/home/.local/lib/python3.8/site-packages/nonebot/message.py", line 170, in _run_matcher
    await matcher.run(bot, event, state)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 496, in run
    await self.run_handler(handler, bot, event, state_)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 481, in run_handler
    await handler(
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 365, in wrapper
    await matcher.run_handler(func, bot, event, state)
  File "/home/.local/lib/python3.8/site-packages/nonebot/matcher.py", line 481, in run_handler
    await handler(
  File "src/plugins/esports/_query.py", line 80, in handle_event
    query_day = datetime.datetime.strptime(args, "%Y%m%d")
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '22' does not match format '%Y%m%d'

==========================
我现在有点懵（X_X），手头环境也不方便debug，所以只能来发issue啦

**Comment by yyyanbj** [comment]
emm，第一个确实有点小问题！已经修复啦，非常感谢:laughing:！~~稍后会push上来~~ 以pr #10，ps.换了一种更好的表达形式`(query_day.date() - datetime.datetime.now().date()).days`
不过对于后面两个问题，重复发消息的问题应该在之前的pr(#6) 已经修复过啦，主要原因是在`__init__.py`中包的调用形式应该是从根目录写起，我这边没办法复现到这个问题哎，你看一下你的插件是否叫做esports，有没有esport插件，有的话应该将esport删除掉，只保留epsorts，或者可以添加测试qq来进行测试:kissing_heart:

**Comment by Jerry-FaGe** [comment]
> emm，第一个确实有点小问题！已经修复啦，非常感谢😆！~稍后会push上来~ 以pr #10，ps.换了一种更好的表达形式`(query_day.date() - datetime.datetime.now().date()).days`
> 不过对于后面两个问题，重复发消息的问题应该在之前的pr(#6) 已经修复过啦，主要原因是在`__init__.py`中包的调用形式应该是从根目录写起，我这边没办法复现到这个问题哎，你看一下你的插件是否叫做esports，有没有esport插件，有的话应该将esport删除掉，只保留epsorts，或者可以添加测试qq来进行测试😘

突然发现我给的建议代码根本就是错的（丢人），后面的问题也解决了，由于我是用原生nonebot2加插件，你的插件加过去基本都要改import，当时偷懒`__init__.py`直接`import ._qxxxx`了😆改成从根目录导入就好了

另外提个建议⑧，现在的更新日志没写改了哪个插件的哪个bug不方便用户维护唉，要去commit里一点一点找。不过问题不大不着急改

**Comment by yyyanbj** [comment]
前面那个你可以直接复制整个`awesome`文件夹，然后在`bot.py`中加一句`nonebot.load_plugins("awesome_bot/plugins")`就好~
后面的问题我会注意的哈哈哈哈，以后尽量现在`dev`分支里测试完在push到主分支里，现在版本管理有一点点混乱，后续更新日志可能会放在wiki中！感谢:heart:~
